<?php

namespace MigratorTest;

use Migrator\MigratorServiceProvider;
use Livewire\LivewireServiceProvider;

abstract class TestCase extends \Orchestra\Testbench\TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function getPackageProviders($app)
    {
        return [
            MigratorServiceProvider::class,
            LivewireServiceProvider::class
        ];
    }
}
